### ISSUE TITLE
Add scripts for image writing with progress tracking

### ISSUE THREAD

**Issue by eyalroz** [satk0/usbdrivetools#1]
A common action with USB drivers is writing entire drive or partition images to them (rather than individual files).

It would be nice if this package included a script for doing so and actually tracking progress.

**Comment by satk0** [comment]
Nice idea. So you think about some script named `usbimgwrite` that would use `dd` and then track `sync` command, am I right?

**Comment by eyalroz** [comment]
I think so...

but there are some discussions of this matter on StackExchange, especially with regard to whether or not to use any `conv` flags for dd:

* [[dd command oflag direct and sync flags](https://unix.stackexchange.com/questions/508701/dd-command-oflag-direct-and-sync-flags)](https://unix.stackexchange.com/questions/508701/dd-command-oflag-direct-and-sync-flags)
* [When writing an ISO image to USB flash drive with dd, how do I know I can remove the stick?](https://unix.stackexchange.com/questions/668687/when-writing-an-iso-image-to-usb-flash-drive-with-dd-how-do-i-know-i-can-remove)
* [Can I watch the progress of a `sync` operation?](https://unix.stackexchange.com/questions/48235/can-i-watch-the-progress-of-a-sync-operation)](https://unix.stackexchange.com/questions/48235/can-i-watch-the-progress-of-a-sync-operation)
* [How to prevent dd's progress from being meaningless on Linux?](https://unix.stackexchange.com/questions/379947/how-to-prevent-dds-progress-from-being-meaningless-on-linux)

**Comment by satk0** [comment]
Oh yea, the more people the more opinions :smile: 

`dd ... && sync` approach would be the easiest to implement.

I might try to mess with the `dd ... conv=fsync` as it supposedly reports whether one of the writes failed.

**Comment by satk0** [comment]
Hey @eyalroz, I added your requested feature.

The new script is called `usbdd`

Please check it out in your free time and if it works as you expected, I will close the issue :sweat_smile: .

**Comment by satk0** [comment]
I am closing this issue. Let me know if something works wrong in a new one.
